[2024-11-17T20:44:22.057+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-17T20:44:22.071+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_store_normalized_airbnb_data.scrape_airbnb_data manual__2024-11-17T20:29:25.323662+00:00 [queued]>
[2024-11-17T20:44:22.076+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_store_normalized_airbnb_data.scrape_airbnb_data manual__2024-11-17T20:29:25.323662+00:00 [queued]>
[2024-11-17T20:44:22.077+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 3
[2024-11-17T20:44:22.086+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): scrape_airbnb_data> on 2024-11-17 20:29:25.323662+00:00
[2024-11-17T20:44:22.094+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=124) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-17T20:44:22.095+0000] {standard_task_runner.py:72} INFO - Started process 126 to run task
[2024-11-17T20:44:22.095+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_store_normalized_airbnb_data', 'scrape_airbnb_data', 'manual__2024-11-17T20:29:25.323662+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp5fid6ssj']
[2024-11-17T20:44:22.096+0000] {standard_task_runner.py:105} INFO - Job 31: Subtask scrape_airbnb_data
[2024-11-17T20:44:22.129+0000] {task_command.py:467} INFO - Running <TaskInstance: scrape_and_store_normalized_airbnb_data.scrape_airbnb_data manual__2024-11-17T20:29:25.323662+00:00 [running]> on host e70f175ad631
[2024-11-17T20:44:22.182+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scrape_and_store_normalized_airbnb_data' AIRFLOW_CTX_TASK_ID='scrape_airbnb_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-17T20:29:25.323662+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-17T20:29:25.323662+00:00'
[2024-11-17T20:44:22.183+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-17T20:44:22.184+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-17T20:44:22.184+0000] {logging_mixin.py:190} INFO - Current task name:scrape_airbnb_data state:running start_date:2024-11-17 20:44:22.071721+00:00
[2024-11-17T20:44:22.184+0000] {logging_mixin.py:190} INFO - Dag name:scrape_and_store_normalized_airbnb_data and current dag run status:running
[2024-11-17T20:44:22.185+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-17T20:44:22.800+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 20, in scrape_airbnb_data
    raise ValueError("Table not found on the page.")
ValueError: Table not found on the page.
[2024-11-17T20:44:22.810+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-17T20:44:22.810+0000] {logging_mixin.py:190} INFO - Task start:2024-11-17 20:44:22.071721+00:00 end:2024-11-17 20:44:22.810073+00:00 duration:0.738352
[2024-11-17T20:44:22.811+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): scrape_airbnb_data> dag:<DAG: scrape_and_store_normalized_airbnb_data> dagrun:<DagRun scrape_and_store_normalized_airbnb_data @ 2024-11-17 20:29:25.323662+00:00: manual__2024-11-17T20:29:25.323662+00:00, state:running, queued_at: 2024-11-17 20:44:20.415596+00:00. externally triggered: True>
[2024-11-17T20:44:22.811+0000] {logging_mixin.py:190} INFO - Failure caused by Table not found on the page.
[2024-11-17T20:44:22.811+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=scrape_and_store_normalized_airbnb_data, task_id=scrape_airbnb_data, run_id=manual__2024-11-17T20:29:25.323662+00:00, execution_date=20241117T202925, start_date=20241117T204422, end_date=20241117T204422
[2024-11-17T20:44:22.819+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-17T20:44:22.820+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 31 for task scrape_airbnb_data (Table not found on the page.; 126)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 20, in scrape_airbnb_data
    raise ValueError("Table not found on the page.")
ValueError: Table not found on the page.
[2024-11-17T20:44:22.831+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-17T20:44:22.846+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-17T20:44:22.849+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
