[2024-11-21T00:54:55.340+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-21T00:54:55.355+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_store_airbnb_data.scrape_airbnb_data manual__2024-11-20T21:30:27.250542+00:00 [queued]>
[2024-11-21T00:54:55.361+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_store_airbnb_data.scrape_airbnb_data manual__2024-11-20T21:30:27.250542+00:00 [queued]>
[2024-11-21T00:54:55.363+0000] {taskinstance.py:2866} INFO - Starting attempt 10 of 10
[2024-11-21T00:54:55.375+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): scrape_airbnb_data> on 2024-11-20 21:30:27.250542+00:00
[2024-11-21T00:54:55.383+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=103) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-21T00:54:55.384+0000] {standard_task_runner.py:72} INFO - Started process 105 to run task
[2024-11-21T00:54:55.385+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_store_airbnb_data', 'scrape_airbnb_data', 'manual__2024-11-20T21:30:27.250542+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp8w4598jk']
[2024-11-21T00:54:55.386+0000] {standard_task_runner.py:105} INFO - Job 62: Subtask scrape_airbnb_data
[2024-11-21T00:54:55.435+0000] {task_command.py:467} INFO - Running <TaskInstance: scrape_and_store_airbnb_data.scrape_airbnb_data manual__2024-11-20T21:30:27.250542+00:00 [running]> on host b3a8bb7dbe23
[2024-11-21T00:54:55.904+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scrape_and_store_airbnb_data' AIRFLOW_CTX_TASK_ID='scrape_airbnb_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-20T21:30:27.250542+00:00' AIRFLOW_CTX_TRY_NUMBER='10' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-20T21:30:27.250542+00:00'
[2024-11-21T00:54:55.905+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-21T00:54:55.906+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-21T00:54:55.906+0000] {logging_mixin.py:190} INFO - Current task name:scrape_airbnb_data state:running start_date:2024-11-21 00:54:55.356001+00:00
[2024-11-21T00:54:55.907+0000] {logging_mixin.py:190} INFO - Dag name:scrape_and_store_airbnb_data and current dag run status:running
[2024-11-21T00:54:55.907+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-21T00:55:35.718+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-11-21T00:55:35.720+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-21T00:55:35.722+0000] {process_utils.py:132} INFO - Sending 15 to group 105. PIDs of all processes in the group: [105]
[2024-11-21T00:55:35.722+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 105
[2024-11-21T00:55:35.723+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-21T00:55:35.732+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 39, in scrape_airbnb_data
    data = fetch_all_data(limit=100)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 28, in fetch_all_data
    batch = fetch_airbnb_data(limit=limit, offset=offset)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 18, in fetch_airbnb_data
    response = requests.get(url, params=params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 730, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.12/ssl.py", line 1319, in do_handshake
    self._sslobj.do_handshake()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-11-21T00:55:35.741+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-21T00:55:35.741+0000] {logging_mixin.py:190} INFO - Task start:2024-11-21 00:54:55.356001+00:00 end:2024-11-21 00:55:35.740917+00:00 duration:40.384916
[2024-11-21T00:55:35.742+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): scrape_airbnb_data> dag:<DAG: scrape_and_store_airbnb_data> dagrun:<DagRun scrape_and_store_airbnb_data @ 2024-11-20 21:30:27.250542+00:00: manual__2024-11-20T21:30:27.250542+00:00, state:running, queued_at: 2024-11-21 00:54:53.987819+00:00. externally triggered: True>
[2024-11-21T00:55:35.742+0000] {logging_mixin.py:190} INFO - Failure caused by Task received SIGTERM signal
[2024-11-21T00:55:35.742+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=scrape_and_store_airbnb_data, task_id=scrape_airbnb_data, run_id=manual__2024-11-20T21:30:27.250542+00:00, execution_date=20241120T213027, start_date=20241121T005455, end_date=20241121T005535
[2024-11-21T00:55:35.754+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-21T00:55:35.775+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=105, status='terminated', exitcode=2, started='00:54:55') (105) terminated with exit code 2
